title: Jess Stephenson
author: Jess Stephenson
email: jess.stephenson@nyu.edu
baseurl: "" # Leave empty if deploying to the root of a domain
url: "https://jessdstephenson.github.io"

plugins:
  - jekyll-seo-tag # Add plugins as needed

logo: "/me.jpg"

