remote_theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: My GitHub Page
description: A simple site using the Cayman theme
